#! /bin/bash

# Display
xrandr --newmode "1152x864_60.00"   81.75  1152 1216 1336 1520  864 867 871 897 -hsync +vsync ;
xrandr --addmode VGA1 "1152x864_60.00" ; xrandr --output VGA1 --mode "1152x864_60.00"

# StartUp
sh ~/.config/bspwm/gifwal.sh &
sh ~/.config/bspwm/startup.sh &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom/picom.conf &

# Workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Windows Style
bspc config border_width	4
bspc config window_gap		6

bspc config focused_border_color	"#825CAD" 
bspc config normal_border_color		"#B5C6E5"
bspc config active_border_color 	"#D584E7"
bspc config presel_feedback_color 	"#EC94B1"

# Windows Properties
bspc config split_ratio 		0.52
bspc config single_monocle 		false
bspc config focus_follows_pointer 	true
bspc config borderless_monocle 		true
bspc config gapless_monocle 		true
